name: sooraneh_mobile
description: مدیریت مالی شخصی و خانوادگی - Sooraneh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  persian_date: ^0.1.5
  get: ^4.6.6
  flutter_spinkit: ^5.2.0
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
